### ISSUE TITLE
Suggestion: Add Database Initialization Script

### ISSUE THREAD

**Issue by notstripes** [rohitmondal03/OpenTyped#1]
## Problem
The project doesn’t have a database initialization script or sample data.

## Solution
Add a SQL script or a Prisma migration file to create the necessary tables and insert sample data. Update the `README.md` to include instructions on how to run the script.

## Why
Currently it is impossible for an open source developer to access any portion of the page requiring use of prisma, as there is no way of initializing a database.

**Comment by rohitmondal03** [comment]
@nicholas-vecchio thanks fro opening an issue. Are you saying to update `README.md` file ?

**Comment by notstripes** [comment]
@rohitmondal03 Apologies for being slightly vague. What I mean is you should provide a method for others to access or create the database you are using for your web application, whether that simply be through an SQL script file or something like docker.

**Comment by rohitmondal03** [comment]
> @rohitmondal03 Apologies for being slightly vague. What I mean is you should provide a method for others to access or create the database you are using for your web application, whether that simply be through an SQL script file or something like docker.

Actually, prisma will only be accessible by running some CLI commands. I'll update the README.md as soon as possible.

**Comment by rohitmondal03** [comment]
Do you want to contribute to this project ??
